name: Build
run-name: Build on ${{ github.sha }}

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  Build-on-Linux:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
    - name: Check out repository code
      uses: actions/checkout@v4
      with:
        ref: ${{ github.ref }}

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install gcc make sed xxd libc6-dev libx11-dev libxmu-dev libunistring-dev libmicrohttpd-dev

    - name: Build
      run: make
